---
 - hosts: all
   become: true
   tasks:
       - name: download unzip
         apt: name=unzip state=present update_cache=yes

       - name: create group
         group: name=tomcat state=present

       - name: create user
         user: name=tomcat group=tomcat state=present

       - name: create directory
         file: path=/opt/tomcat state=directory owner=tomcat group=tomcat

       - name: change permission
         file: path=/opt/tomcat mode=777
   
       - name: download package
         get_url: url=http://mirrors.estointernet.in/apache/tomcat/tomcat-7/v7.0.91/bin/apache-tomcat-7.0.91.zip dest=/opt/tomcat/

       - name: Unarchive a file that needs to be downloaded (added in 2.0)
         unarchive: src=/opt/tomcat/apache-tomcat-7.0.91.zip dest=/opt/tomcat/ remote_src=yes

       - name: download war
         get_url: url=https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war dest=/opt/tomcat/apache-tomcat-7.0.91/webapps mode=777

       - name: make .sh files executable
         file: path=/opt/tomcat/apache-tomcat-7.0.91/bin/*.sh mode=777 state=present

